name: Elixir Pipeline

env:
  ELIXIR_VERSION: 1.11.2
  OTP_VERSION: 23

on:
  push: 
    branches: [ .* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        elixir-version:  ${{ env.ELIXIR_VERSION }} # Define the elixir version [required]
        otp-version:  ${{ env.OTP_VERSION }} # Define the OTP version [required]

    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    # - name: Check formatting
    #   run: mix format --check-formatted

    - name: Run Credo
      run: mix credo --strict -i FIXME

    - name: Run tests
      run: mix test
